# Generated by Django 4.0.4 on 2022-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.IntegerField(help_text='Price in $ (USD)')),
                ('sale_type', models.CharField(choices=[('FOR_SALE', 'For sale'), ('FOR_RENT', 'For rent')], help_text='For rent or sale?', max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('nukus', 'Nukus')], max_length=50)),
                ('featured_image', models.ImageField(upload_to='listing/')),
            ],
        ),
    ]
